# Generated by Django 5.2.7 on 2025-10-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifycredentials',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotifycredentials',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotifycredentials',
            name='scope',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotifycredentials',
            name='token_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
