# Generated by Django 5.2.7 on 2025-11-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='embed',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
