# Generated by Django 5.2.7 on 2025-12-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0002_matchweightsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifycredentials',
            name='expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
