# Generated by Django 5.2.7 on 2025-10-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0002_user_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
