# Generated by Django 5.2.7 on 2025-10-09 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmony', '0003_alter_user_options_alter_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
